=== x0xolenok/Web-programming-technologies/LR 8/Pr.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="header">
		<xs:sequence>
			<xs:element type="xs:string" name="ph1"/>
			<xs:element type="xs:string" name="ph2"/>
			<xs:element type="xs:string" fixed="" name="border"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="paragraph" mixed="true">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element type="xs:string" name="a" minOccurs="0"/>
				<xs:element type="xs:string" name="light" minOccurs="0"/>
				<xs:element type="paragraph" name="center" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="image">
		<xs:sequence>
			<xs:element type="xs:string" name="caption"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="empty"/>

	<xs:complexType name="page">
		<xs:sequence>
			<xs:element type="header" name="header"/>
			<xs:sequence>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element type="paragraph" name="p" minOccurs="0"/>
					<xs:element type="paragraph" name="pre" minOccurs="0"/>
					<xs:element type="empty" name="br" minOccurs="0"/>
					<xs:element type="image" name="img" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="body">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="page" name="page"/>
				<xs:element type="empty" name="nextpage"/>
				<xs:element type="page" name="page"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== x0xolenok/Web-programming-technologies/LR 8/Pr.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/css" href="first.css"?>
<!DOCTYPE body SYSTEM "def.dtd">
<body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Pr.xsd">
    <page>
		<header>
			<ph1>
				8
			</ph1>

			<ph2>
				Тема1
			</ph2>

			<border/>
		</header>

        <img>
            <caption>
                Рисунок 1.1. Объединение сетей в Интернет
            </caption>
        </img>

        <br/>

        <p>
            <a>Веб-страница</a> – гипертекстовой ресурс Всемирной паутины,
            обычно написанный на языке HTML.
            Веб-страница может содержать ссылки для перехода на другие страницы,
            а также изображения, медиафайлы, например звуковые файлы и видео,
            Flash-анимацию и т.п.
        </p>

        <br/>

        <p>
            Программа, демонстрирующая веб-страницу,
            называется <a>веб-браузер.</a>
            Несколько веб-страниц, объединенных общей темой и дизайном, образуют <a>веб-сайт.</a>
        </p>

        <br/>

        <p>
            <a>Веб-сервер (HTTP-сервер)</a> – это программное обеспечение (ПО),
            предоставляющее доступ к сайтам. Наиболее популярными веб-серверами являются
            Apache (для ОС Windows и Unix) и Microsoft IIS (для Windows).
            Также вебсервером называют компьютер, на котором установлено такое ПО.
        </p>

        <br/>

        <pre>URL (Uniform Resource Locator) – адрес ресурса.
Структура URL:
<center><light>протокол :// пользователь : пароль @ хост : порт / путь ? запрос</light></center></pre>

    </page>

    <nextpage/>

    <page>
		<header>
			<ph1>
				Содержание
			</ph1>

			<ph2>
				9
			</ph2>

			<border/>
		</header>

        <p>
            Некоторые элементы URL могут быть опущены. Чаще всего адрес имеет вид <light>протокол :// хост / путь</light>,
        </p>

        <pre>где протокол – <light>http, https, ftp, skype</light> и др.
            хост – доменное имя (или IP-адрес)
            путь – местонахождение ресурса на хосте</pre>

        <br/>

        <p>
            Например: http://www.redut.ru/forum/index.php
        </p>

        <p>
            При помощи URL можно ссылаться на любой открытый ресурс, будь то страница, изображение, файл для загрузки и т.д.
        </p>

        <br/>

        <pre>Для обращения к сайту используют <a>доменное имя</a> Доменное имя состоит из нескольких доменов, разделенных точкой.
Например:
maps.google.com – означает, что домен третьего уровня maps входит в домен второго уровня google, который в свою очередь входит в домен первого (верхнего) уровня com.</pre>

        <br/>

        <pre>Домены верхнего уровня делятся на общие и географические. Общие домены предназначены для определенного класса организаций, например:
.com – для коммерческих сайтов;
.org – для некоммерческих организаций;
.net – для сайтов, чья деятельность связана с Интернетом.</pre>

        <br/>

        <pre>Географические домены выделяются для конкретной страны, например:
.ru – Россия;
.us – США;
.eu – Европейский союз;
.de – Германия.</pre>

        <br/>

        <p>
            Использование географического домена не всегда означает то, что сайт
            размещается в соответствующей стране или имеет к ней какое-либо отношение.
            Например, многие телекомпании используют домен .tv островного государства Тувалу.
        </p>

        <br/>

        <p>
            Помимо доменного имени для работы сайта необходим
            круглосуточно работающий веб-сервер, способный
            выдержать большие нагрузки. Услуга размещения
            веб-сайта на веб-сервере называется <a>хостингом</a>.
            Хостинг может быть платным или бесплатным.
            На платном хостинге, как правило, предоставляется
            доменное имя второго уровня.
        </p>
    </page>
</body>
